dark_theme: true
show_controls: true
start_with: ''
mode: chat-instruct
chat_style: messenger
prompt-default: QA
prompt-notebook: QA
preset: simple-1
max_new_tokens: 512
max_new_tokens_min: 1
max_new_tokens_max: 4096
negative_prompt: ''
seed: -1
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 200000
max_tokens_second: 0
max_updates_second: 0
custom_stopping_strings: '"<|im_end|>","</s>"'
custom_token_bans: ''
auto_max_new_tokens: false
ban_eos_token: false
add_bos_token: true
skip_special_tokens: false
stream: true
character: "story01\u52A9\u624B"
name1: "\u4FA6\u63A2"
custom_system_message: ''
instruction_template_str: |-
  {%- set ns = namespace(found=false) -%}
  {%- for message in messages -%}
      {%- if message['role'] == 'system' -%}
          {%- set ns.found = true -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if not ns.found -%}
      {{- '<|im_start|>system\n' + '' + '<|im_end|>\n' -}}
  {%- endif %}
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{-'<|im_start|>user\n' + message['content'] + '<|im_end|>\n'-}}
          {%- else -%}
              {{-'<|im_start|>assistant\n' + message['content'] + '<|im_end|>\n' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if add_generation_prompt -%}
      {{-'<|im_start|>assistant\n'-}}
  {%- endif -%}
chat_template_str: |-
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- message['content'] + '\n\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{- name1 + ': ' + message['content'] + '\n'-}}
          {%- else -%}
              {{- name2 + ': ' + message['content'] + '\n' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
chat-instruct_command: "\u7EE7\u7EED\u4E0B\u9762\u7684\u5BF9\u8BDD\uFF0C\u8BF7\u5199\u51FA\u89D2\u8272 \"<|character|>\"\u7684\u56DE\u7B54\u3002\n\n<|prompt|>"
autoload_model: false
gallery-items_per_page: 50
gallery-open: false
knowledge_base: true
knowledge_base_name: story01_assistant
default_extensions:
- gallery
